project_name: cloud-platform-cli
env:
  - DOCKERFILE=Dockerfile-goreleaser
before:
  hooks:
    - go mod download
    - scripts/completions.sh
archives:
  - files:
      - README.md
      - LICENSE
      - completions/*
builds:
  - main: ./main.go
    binary: cloud-platform
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/jackstockley89/cloud-platform-cli/pkg/commands.Version={{.Version}} -X github.com/jackstockley89/cloud-platform-cli/pkg/commands.Commit={{.Commit}} -X github.com/jackstockley89/cloud-platform-cli/pkg/commands.Date={{ .CommitDate }}
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - go mod tidy
brews:
  - tap:
      owner: jackstockley89
      name: homebrew-cloud-platform-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://user-guide.cloud-platform.service.justice.gov.uk/#cloud-platform-user-guide
    description: Multi-purpose CLI for Ministry of Justice Cloud Platform.
    license: MIT
    install: |-
      bin.install "cloud-platform"
      bash_completion.install "completions/cloud-platform.bash" => "cloud-platform"
      zsh_completion.install "completions/cloud-platform.zsh" => "_cloud-platform"
      fish_completion.install "completions/cloud-platform.fish"
    dependencies:
      - name: go
dockers:
  - image_templates: [ "jackstockley89/{{ .ProjectName }}:{{ .Tag}}-amd64" ]
    goarch: amd64
    dockerfile: '{{ .Env.DOCKERFILE }}'
    use: buildx
    build_flag_templates:
      - --build-arg=CLOUD_PLATFORM_CLI_VERSION={{ .Tag}}
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/jackstockley89/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/jackstockley89/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT License
  # - image_templates: [ "jackstockley89/{{ .ProjectName }}:{{ .Tag}}-arm64" ]
  #   goarch: arm64
  #   dockerfile: '{{ .Env.DOCKERFILE }}'
  #   use: buildx
  #   build_flag_templates:
  #     - --build-arg=CLOUD_PLATFORM_CLI_VERSION={{ .Tag}}
  #     - --platform=linux/arm64
  #     - --label=org.opencontainers.image.title={{ .ProjectName }}
  #     - --label=org.opencontainers.image.description={{ .ProjectName }}
  #     - --label=org.opencontainers.image.url=https://github.com/jackstockley89/{{ .ProjectName }}
  #     - --label=org.opencontainers.image.source=https://github.com/jackstockley89/{{ .ProjectName }}
  #     - --label=org.opencontainers.image.version={{ .Version }}
  #     - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  #     - --label=org.opencontainers.image.revision={{ .FullCommit }}
  #     - --label=org.opencontainers.image.licenses=MIT License
  # - image_templates: [ "jackstockley89/{{ .ProjectName }}:{{ .Tag}}-arm" ]
  #   goarch: arm
  #   dockerfile: '{{ .Env.DOCKERFILE }}'
  #   use: buildx
  #   build_flag_templates:
  #     - --build-arg=CLOUD_PLATFORM_CLI_VERSION={{ .Tag}}
  #     - --platform=linux/arm
  #     - --label=org.opencontainers.image.title={{ .ProjectName }}
  #     - --label=org.opencontainers.image.description={{ .ProjectName }}
  #     - --label=org.opencontainers.image.url=https://github.com/jackstockley89/{{ .ProjectName }}
  #     - --label=org.opencontainers.image.source=https://github.com/jackstockley89/{{ .ProjectName }}
  #     - --label=org.opencontainers.image.version={{ .Version }}
  #     - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  #     - --label=org.opencontainers.image.revision={{ .FullCommit }}
  #     - --label=org.opencontainers.image.licenses=MIT License
  # - image_templates: [ "jackstockley89/{{ .ProjectName }}:{{ .Tag}}-386" ]
  #   goarch: "386"
  #   dockerfile: '{{ .Env.DOCKERFILE }}'
  #   use: buildx
  #   build_flag_templates:
  #     - --build-arg=CLOUD_PLATFORM_CLI_VERSION={{ .Tag}}
  #     - --platform=linux/386
  #     - --label=org.opencontainers.image.title={{ .ProjectName }}
  #     - --label=org.opencontainers.image.description={{ .ProjectName }}
  #     - --label=org.opencontainers.image.url=https://github.com/jackstockley89/{{ .ProjectName }}
  #     - --label=org.opencontainers.image.source=https://github.com/jackstockley89/{{ .ProjectName }}
  #     - --label=org.opencontainers.image.version={{ .Version }}
  #     - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  #     - --label=org.opencontainers.image.revision={{ .FullCommit }}
  #     - --label=org.opencontainers.image.licenses=MIT License

docker_manifests: 
  - name_template: "jackstock8904/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "jackstock8904/{{ .ProjectName }}:{{ .Tag }}-amd64"
  - name_template: "jackstock8904/{{ .ProjectName }}:latest"
    image_templates: 
      - "jackstock8904/{{ .ProjectName }}:{{ .Tag }}-amd64"

announce:
  slack:
    enabled: true
    message_template: '{{ .ProjectName }} {{ .Tag }}: The latest release has been created successfully: {{ .ReleaseURL }}'